#ifndef GLOBAL_TESTING_H
#define GLOBAL_TESTING_H

#define TESTS 0
#define TEST_DERIVATIVES_MODULE 0
#define TEST_MPI_MODULE 0
#define TEST_ITERATIVE_SOLVER 1
#define TEST_CURVE_FITTING 0
#define TEST_RHS_FUNCTIONS 0

#endif // GLOBAL_TESTING_H