#ifndef ARRAY_DEALLOCATION_DEALLOCATE_FUNCTIONS_H
#define ARRAY_DEALLOCATION_DEALLOCATE_FUNCTIONS_H

void deallocate_2D_array(double **array_ptr);

#endif // ARRAY_DEALLOCATION_DEALLOCATE_FUNCTIONS_H
